INSERT INTO transactions
SELECT gen_random_uuid(),CASE WHEN i=1 THEN 'abc-123' ELSE 'tx-'||lpad(i::text,3,'0') END,'usr-'||lpad((((i-1)%50)+1)::text,3,'0'),'rec-'||lpad(i::text,4,'0'),'TR720001002136978165'||lpad((((i-1)%50)+1)::text,6,'0'),(100+i*3.25)::numeric(19,2),'TRY',CASE WHEN i>450 THEN 'REBATE' ELSE 'PAYMENT' END,CASE WHEN i=3 OR (i BETWEEN 451 AND 483 AND i NOT IN (452,453,455)) OR (i<=450 AND i%29=0) THEN 'FAILED' ELSE 'SUCCESS' END,now()-interval '23 hours'+i*interval '2 minutes',now()-interval '23 hours'+i*interval '2 minutes'+interval '5 seconds' FROM generate_series(1,500) i;
INSERT INTO payments SELECT gen_random_uuid(),transaction_id,amount,'MOBILE','WALLET',status,created_at+interval '1 second' FROM transactions WHERE transaction_type='PAYMENT';
INSERT INTO account_transactions SELECT gen_random_uuid(),transaction_id,amount,'SUCCESS',created_at+interval '3 seconds' FROM transactions WHERE transaction_type='PAYMENT' AND status='SUCCESS' AND transaction_id<>'tx-005';
INSERT INTO rebates SELECT gen_random_uuid(),CASE WHEN i=1 THEN 'abc-123' ELSE 'tx-'||lpad(i::text,3,'0') END,'tx-'||(450+i),10,CASE WHEN (i<=33 AND i NOT IN (2,3,5)) THEN 'FAILED' ELSE 'SUCCESS' END,CASE WHEN i=4 THEN 'Duplicate rebate request' WHEN (i<=33 AND i NOT IN (2,3,5)) THEN 'Refundable balance is zero' ELSE NULL END,now()-interval '23 hours'+i*interval '2 minutes'+interval '209 seconds' FROM generate_series(1,50) i;
UPDATE transactions t SET amount=r.amount,created_at=r.created_at,updated_at=r.created_at+interval '1 second' FROM rebates r WHERE t.transaction_id=r.rebate_transaction_id;
INSERT INTO service_logs SELECT gen_random_uuid(),CASE WHEN j=2 THEN 'wallet-service' WHEN t.transaction_type='REBATE' THEN 'rebate-service' ELSE 'payment-service' END,'INFO',CASE WHEN j=2 THEN 'Wallet service request sent' WHEN t.transaction_type='REBATE' THEN 'Rebate request received' ELSE 'Payment request received' END,'req-'||lpad(i::text,3,'0'),'corr-'||lpad(i::text,3,'0'),t.transaction_id,'{"source":"synthetic"}',NULL,NULL,t.created_at+(j-1)*interval '500 milliseconds' FROM generate_series(1,500)i JOIN transactions t ON t.transaction_id=CASE WHEN i=1 THEN 'abc-123' ELSE 'tx-'||lpad(i::text,3,'0') END CROSS JOIN generate_series(1,2)j;
INSERT INTO service_logs SELECT gen_random_uuid(),'wallet-service','ERROR',failure_reason,'req-rebate-'||rebate_transaction_id,'corr-rebate-'||rebate_transaction_id,original_transaction_id,'{"operation":"rebate","amount":10}',json_build_object('error',failure_reason)::text,400,created_at+interval '1 second' FROM rebates WHERE status='FAILED';
INSERT INTO service_logs VALUES(gen_random_uuid(),'wallet-service','ERROR','Wallet Service timeout; downstream outcome unknown','req-003','corr-003','tx-003','{"operation":"payment"}','{"error":"timeout"}',504,now()-interval '23 hours'+interval '6 minutes 4 seconds');
INSERT INTO kafka_events SELECT gen_random_uuid(),'payment.completed',transaction_id,transaction_id,json_build_object('transactionId',transaction_id,'event','payment.completed')::text,CASE WHEN transaction_id='tx-002' THEN 'FAILED' ELSE 'SUCCESS' END,created_at+interval '2 seconds' FROM transactions WHERE transaction_type='PAYMENT' ORDER BY created_at LIMIT 100;
INSERT INTO incidents SELECT gen_random_uuid(),'INC-'||(1800+i),CASE WHEN i=2 THEN 'Kafka delivery failed' WHEN i=3 THEN 'Wallet payment timeout' WHEN i=4 THEN 'Duplicate rebate request' WHEN i=5 THEN 'Account transaction missing' ELSE 'Wallet rebate HTTP 400' END,'Synthetic incident for evidence-driven investigation',CASE WHEN i=1 THEN 'abc-123' ELSE 'tx-'||lpad(i::text,3,'0') END,CASE WHEN i>15 THEN 'RESOLVED' WHEN i%3=0 THEN 'INVESTIGATING' ELSE 'OPEN' END,CASE WHEN i<=3 THEN 'CRITICAL' WHEN i%2=0 THEN 'HIGH' ELSE 'MEDIUM' END,CASE WHEN i>15 THEN 'Wallet rebate rejected: refundable balance is zero' ELSE NULL END,now()-i*interval '20 minutes',CASE WHEN i>15 THEN now() ELSE NULL END FROM generate_series(1,20)i;
