CREATE TABLE app_users (id uuid PRIMARY KEY, user_id varchar(80) UNIQUE NOT NULL, email varchar(160) UNIQUE NOT NULL, name varchar(160) NOT NULL, password_hash varchar(100) NOT NULL, role varchar(30) NOT NULL CHECK(role IN ('ADMIN','SUPPORT_ENGINEER','VIEWER')), iban varchar(34) UNIQUE NOT NULL);
CREATE TABLE transactions (id uuid PRIMARY KEY, transaction_id varchar(80) UNIQUE NOT NULL, user_id varchar(80) NOT NULL REFERENCES app_users(user_id), reconciliation_id varchar(80) UNIQUE NOT NULL, iban varchar(34) NOT NULL, amount numeric(19,2) NOT NULL CHECK(amount>=0), currency varchar(3) NOT NULL, transaction_type varchar(20) NOT NULL CHECK(transaction_type IN ('PAYMENT','REBATE','TRANSFER','REFUND')), status varchar(20) NOT NULL CHECK(status IN ('CREATED','PROCESSING','SUCCESS','FAILED','CANCELLED')), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE payments (id uuid PRIMARY KEY, transaction_id varchar(80) NOT NULL REFERENCES transactions(transaction_id), amount numeric(19,2) NOT NULL, channel_type varchar(30) NOT NULL, account_type varchar(30) NOT NULL, status varchar(30) NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE account_transactions (id uuid PRIMARY KEY, transaction_id varchar(80) NOT NULL REFERENCES transactions(transaction_id), amount numeric(19,2) NOT NULL, status varchar(30) NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE rebates (id uuid PRIMARY KEY, original_transaction_id varchar(80) NOT NULL REFERENCES transactions(transaction_id), rebate_transaction_id varchar(80) NOT NULL REFERENCES transactions(transaction_id), amount numeric(19,2) NOT NULL, status varchar(30) NOT NULL, failure_reason text, created_at timestamptz NOT NULL);
CREATE TABLE service_logs (id uuid PRIMARY KEY, service_name varchar(80) NOT NULL, level varchar(20) NOT NULL, message text NOT NULL, request_id varchar(80), correlation_id varchar(80), transaction_id varchar(80) REFERENCES transactions(transaction_id), request_body text, response_body text, http_status integer, created_at timestamptz NOT NULL);
CREATE TABLE kafka_events (id uuid PRIMARY KEY, topic varchar(100) NOT NULL, event_key varchar(80) NOT NULL, transaction_id varchar(80) NOT NULL REFERENCES transactions(transaction_id), payload text NOT NULL, status varchar(30) NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE incidents (id uuid PRIMARY KEY, incident_id varchar(80) UNIQUE NOT NULL, title varchar(180) NOT NULL, description text NOT NULL, transaction_id varchar(80) NOT NULL REFERENCES transactions(transaction_id), status varchar(30) NOT NULL CHECK(status IN ('OPEN','INVESTIGATING','RESOLVED','CLOSED')), severity varchar(20) NOT NULL CHECK(severity IN ('LOW','MEDIUM','HIGH','CRITICAL')), root_cause text, created_at timestamptz NOT NULL, resolved_at timestamptz);
CREATE TABLE incident_analyses (id uuid PRIMARY KEY, incident_id uuid REFERENCES incidents(id), transaction_id varchar(80) NOT NULL REFERENCES transactions(transaction_id), root_cause text NOT NULL, confidence numeric(4,3) NOT NULL, evidence text NOT NULL, provider varchar(40) NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE audit_logs (id uuid PRIMARY KEY, user_id varchar(80) NOT NULL, action varchar(80) NOT NULL, resource_type varchar(80) NOT NULL, resource_id varchar(100) NOT NULL, metadata text NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE query_previews (id uuid PRIMARY KEY, user_id varchar(80) NOT NULL, sql_text text NOT NULL, created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE outbox_events (id uuid PRIMARY KEY, transaction_id varchar(80) NOT NULL REFERENCES transactions(transaction_id), payload text NOT NULL, published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX tx_user_idx ON transactions(user_id);
CREATE INDEX tx_iban_idx ON transactions(iban);
CREATE INDEX tx_created_idx ON transactions(created_at);
CREATE INDEX logs_tx_time_idx ON service_logs(transaction_id,created_at);
CREATE INDEX logs_correlation_idx ON service_logs(correlation_id);
CREATE INDEX logs_request_idx ON service_logs(request_id);
CREATE INDEX rebates_original_idx ON rebates(original_transaction_id);
CREATE INDEX rebates_child_idx ON rebates(rebate_transaction_id);
CREATE INDEX payment_tx_idx ON payments(transaction_id);
CREATE INDEX account_tx_idx ON account_transactions(transaction_id);
CREATE INDEX kafka_tx_idx ON kafka_events(transaction_id);
CREATE INDEX incident_tx_idx ON incidents(transaction_id);
CREATE INDEX outbox_pending_idx ON outbox_events(created_at) WHERE published_at IS NULL;

CREATE SCHEMA analytics;
CREATE VIEW analytics.transactions AS SELECT transaction_id,user_id,reconciliation_id,iban,amount,currency,transaction_type,status,created_at,updated_at FROM transactions;
CREATE VIEW analytics.payments AS SELECT transaction_id,amount,channel_type,account_type,status,created_at FROM payments;
CREATE VIEW analytics.rebates AS SELECT original_transaction_id,rebate_transaction_id,amount,status,failure_reason,created_at FROM rebates;
CREATE VIEW analytics.service_logs AS SELECT service_name,level,message,request_id,correlation_id,transaction_id,http_status,created_at FROM service_logs;
CREATE VIEW analytics.kafka_events AS SELECT topic,event_key,transaction_id,status,created_at FROM kafka_events;
CREATE VIEW analytics.incidents AS SELECT incident_id,title,transaction_id,status,severity,root_cause,created_at,resolved_at FROM incidents;
GRANT USAGE ON SCHEMA analytics TO supportops_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO supportops_reader;
