"use client";
import {useEffect,useMemo,useState} from "react";
import {Activity,AlertTriangle,CheckCircle2,ChevronRight,CircleHelp,Copy,CreditCard,LayoutDashboard,LogIn,Moon,RefreshCw,Search,ShieldCheck,Smartphone,Sun,UserRoundSearch,WalletCards,Wrench,XCircle} from "lucide-react";
type State="success"|"error"|"warning";
type Event={id:string;time:string;service:string;action:string;detail:string;state:State;ms:number;amount?:number;code?:string;trace:string};
type Card={type:"wallet"|"flex";last4:string;status:"Aktif"|"Blokeli";expiry:string;label:string};
type User={id:string;name:string;phone:string;wallet:number;flex:number;device:string;risk:string;events:Event[];errors:number;cards:Card[]};
const names=["Ayşe Yılmaz","Mehmet Kara","Selin Demir","Burak Aydın","Zeynep Şahin","Emre Çelik","Elif Kaya","Can Arslan","Deniz Koç","Mert Öztürk","Ece Yıldız","Kerem Aksoy","İrem Kurt","Onur Polat","Seda Güneş","Berk Erdem","Ceren Tunç","Tolga Kaplan","Derya Tekin","Arda Kılıç"];
const devices=["iPhone 15 · iOS 18.6","Galaxy S24 · Android 16","Pixel 9 · Android 16","iPhone 14 · iOS 18.5","Xiaomi 14 · Android 15"];
const issues=[
 ["Money Cüzdan","Ödeme başarısız","İşyeri provizyon isteği zaman aşımına uğradı","WALLET_TIMEOUT"],
 ["Money ProFlex","Haklar görüntülenemedi","Çalışan hakları senkronizasyonu gecikti","FLEX_SYNC_409"],
 ["Money Uygulaması","Oturum yenilenemedi","Refresh token süresi doldu; tekrar giriş gerekli","AUTH_TOKEN_EXPIRED"],
 ["Money Cüzdan","Bakiye uyuşmazlığı","Ledger ile uygulama önbelleği eşleşmedi","BALANCE_MISMATCH"],
 ["Kimlik Servisi","Cihaz doğrulama reddedildi","Yeni cihaz güven doğrulamasını tamamlayamadı","DEVICE_TRUST_403"]
];
const money=(n:number)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(n);
const pad=(n:number)=>String(n).padStart(2,"0");
function events(i:number):Event[]{const day=12-i%4,hour=9+i%9,min=i*7%60,amount=34.5+(i*137)%1850,t=(o:number)=>`${pad(day)} Eyl 2026 · ${pad(hour)}:${pad((min+o)%60)}`,tr=(n:number)=>`tr_${(730041+i*97+n*13).toString(16)}_${pad(i+1)}`;const a:Event[]=[
 {id:`${i}a`,time:t(0),service:"Money Uygulaması",action:"Uygulama açıldı",detail:`${devices[i%5]} üzerinden uygulama başlatıldı`,state:"success",ms:44+i%70,trace:tr(1)},
 {id:`${i}b`,time:t(1),service:"Kimlik Servisi",action:"Kullanıcı girişi",detail:i%6?"SMS OTP doğrulaması tamamlandı":"Biyometrik doğrulama ile oturum açıldı",state:"success",ms:120+i%210,trace:tr(2)},
 {id:`${i}c`,time:t(3),service:"Money Cüzdan",action:"Bakiye sorgulandı",detail:"Kullanılabilir ve bekleyen bakiye getirildi",state:"success",ms:65+i%90,trace:tr(3)},
 {id:`${i}d`,time:t(6),service:i%3?"Money Cüzdan":"Money ProFlex",action:i%3?"QR ile ödeme":"ProFlex ile ödeme",detail:i%4?"Migros mağaza ödemesi":"Migros Sanal Market",state:"success",ms:180+i%240,amount,trace:tr(4)}];
 if(i%3!==1){const x=issues[i%5];a.push({id:`${i}e`,time:t(8),service:x[0],action:x[1],detail:x[2],state:"error",ms:820+i%2100,amount:i%5===0?amount:undefined,code:x[3],trace:tr(5)},{id:`${i}f`,time:t(11),service:x[0],action:"Support kontrolü",detail:i%4===0?"İşlem ikinci denemede tamamlandı":"Olay inceleme kuyruğuna aktarıldı",state:i%4===0?"success":"warning",ms:210+i%300,trace:tr(6)});}
 a.push({id:`${i}g`,time:t(15),service:"Money Uygulaması",action:"Oturum kapandı",detail:"Uygulama arka plana alındı; güvenli oturum sonlandırıldı",state:"success",ms:32+i%45,trace:tr(7)});return a.reverse()}
const users:User[]=Array.from({length:100},(_,i)=>{const e=events(i),cards:Card[]=[];if(i%7!==0)cards.push({type:"wallet",last4:String((i*83+19)%10000).padStart(4,"0"),status:i%13===0?"Blokeli":"Aktif",expiry:`${pad(3+i%9)}/${28+i%5}`,label:"Money Cüzdan Kartı"});if(i%3===0||i%5===0)cards.push({type:"flex",last4:String((i*127+61)%10000).padStart(4,"0"),status:i%17===0?"Blokeli":"Aktif",expiry:`${pad(5+i%7)}/${28+i%5}`,label:"Money ProFlex Kartı"});return{id:`MP-${284019+i*731}`,name:`${names[i%20]} ${i>19?pad(Math.floor(i/20)+1):""}`.trim(),phone:`+90 5${30+i%7} ••• ${pad(i*9%100)} ${pad((i*17+18)%100)}`,wallet:180+(i*347%6800)/10,flex:i%5?250+i*113%1800:0,device:devices[i%5],risk:i%4===0?"Orta":"Düşük",events:e,errors:e.filter(x=>x.state==="error").length,cards}});
const services=[["Money Cüzdan","84 ms","ok",WalletCards],["Money ProFlex","426 ms","warn",CreditCard],["Money Uygulaması","112 ms","ok",Smartphone],["Kimlik Servisi","61 ms","ok",ShieldCheck]] as const;
export default function Home(){const[dark,setDark]=useState(false),[view,setView]=useState<"users"|"logs">("users"),[period,setPeriod]=useState<"daily"|"weekly">("daily"),[q,setQ]=useState(""),[onlyErrors,setOnlyErrors]=useState(false),[cardTab,setCardTab]=useState<"all"|"wallet"|"flex"|"none">("all"),[selectedId,setSelectedId]=useState(users[0].id),[kind,setKind]=useState("all"),[toast,setToast]=useState("");useEffect(()=>{const d=localStorage.getItem("mp-theme")==="dark";setDark(d);document.documentElement.dataset.theme=d?"dark":"light"},[]);const toggle=()=>setDark(v=>{const n=!v;document.documentElement.dataset.theme=n?"dark":"light";localStorage.setItem("mp-theme",n?"dark":"light");return n});const list=useMemo(()=>users.filter(u=>(!onlyErrors||u.errors)&&(cardTab==="all"||cardTab==="none"&&!u.cards.length||u.cards.some(c=>c.type===cardTab))&&(`${u.name} ${u.id} ${u.phone}`.toLocaleLowerCase("tr").includes(q.toLocaleLowerCase("tr")))),[q,onlyErrors,cardTab]);const user=users.find(u=>u.id===selectedId)??users[0];const shown=user.events.filter(e=>kind==="all"||kind==="error"&&e.state==="error"||kind==="payment"&&!!e.amount||kind==="login"&&(e.action.includes("giriş")||e.action.includes("Oturum")));const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2200)};return <main className="portal">
 <aside className="sidebar"><a className="brand" href="#top"><img src="/moneypay-logo.svg" alt="MoneyPay"/><span>Support<br/>Console</span></a><nav><p>OPERASYON</p><button className={view==="users"?"active":""} onClick={()=>setView("users")}><UserRoundSearch/>Kullanıcı Bilgileri</button><button className={view==="logs"?"active":""} onClick={()=>setView("logs")}><Activity/>Servis Log Kontrolü</button><a href="#actions"><Wrench/>Tanı araçları</a></nav><div className="environment"><i/><div><strong>Test ortamı</strong><span>100 sentetik kullanıcı</span></div></div></aside>
 <section className="workspace" id="top"><header className="topbar"><div className="global-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ad, müşteri no veya telefon ara"/></div><button className="theme-toggle" onClick={toggle}>{dark?<Sun/>:<Moon/>}</button><button className="help"><CircleHelp/></button><div className="profile"><span>HK</span><div><strong>Hasan Karyağdı</strong><small>Support Admin</small></div></div></header>
 <div className={`content ${view}-mode`}><div className="section-switch"><button className={view==="users"?"active":""} onClick={()=>setView("users")}><UserRoundSearch/>Kullanıcı Bilgileri</button><button className={view==="logs"?"active":""} onClick={()=>setView("logs")}><Activity/>Servis Log Kontrolü</button></div><section className="page-head"><div><div className="title-row"><h1>Kullanıcı operasyonları</h1><span className="demo-badge">SENTETİK VERİ</span></div><p>Girişten ödeme sonucuna kadar servisler arası tam kullanıcı izini inceleyin.</p></div><div className="live-status"><span><i/>100 profil hazır</span><strong>{users.filter(u=>u.errors).length} hata senaryosu</strong></div></section>
 <section className="service-strip compact log-only" id="services">{services.map(([name,latency,state,Icon])=><article className={`service ${state==="warn"?"degraded":""}`} key={name}><div className="service-top"><span className="service-icon"><Icon/></span><span className={`health ${state==="warn"?"degraded":"healthy"}`}><i/>{state==="warn"?"Yavaşlama":"Sağlıklı"}</span></div><h2>{name}</h2><div className="compact-metric"><span>Yanıt süresi</span><strong>{latency}</strong></div></article>)}</section>
 <section className="user-explorer" id="users"><aside className="user-directory"><div className="directory-head"><div><span className="eyebrow">KULLANICI LİSTESİ</span><h2>100 demo profil</h2></div></div><div className="card-tabs">{([["all","Tümü"],["wallet","Cüzdan"],["flex","ProFlex"],["none","Kartsız"]] as const).map(([key,label])=><button key={key} className={cardTab===key?"active":""} onClick={()=>setCardTab(key)}>{label}<span>{key==="all"?100:key==="none"?users.filter(u=>!u.cards.length).length:users.filter(u=>u.cards.some(c=>c.type===key)).length}</span></button>)}</div><div className="directory-filters"><button className={!onlyErrors?"active":""} onClick={()=>setOnlyErrors(false)}>Tüm durumlar</button><button className={onlyErrors?"active":""} onClick={()=>setOnlyErrors(true)}>Hata alan</button></div><div className="user-list">{list.map(u=><button className={u.id===user.id?"selected":""} key={u.id} onClick={()=>{setSelectedId(u.id);setKind("all")}}><span className="user-avatar">{u.name.split(" ").slice(0,2).map(x=>x[0]).join("")}</span><span className="user-copy"><strong>{u.name}</strong><small>{u.id} · {u.cards.length?u.cards.map(c=>c.type==="wallet"?"Cüzdan":"ProFlex").join(" + "):"Kart atanmamış"}</small></span><span className="user-issue">{u.errors?<><i/>{u.errors} hata</>:<CheckCircle2/>}</span><ChevronRight/></button>)}</div><div className="directory-foot">{list.length} kullanıcı gösteriliyor</div></aside>
 <section className="journey-panel" id="journey"><div className="profile-head"><div className="identity"><span>{user.name.slice(0,2).toUpperCase()}</span><div><span className="eyebrow">KULLANICI YOLCULUĞU</span><h2>{user.name}</h2><p>{user.id} · {user.phone}</p></div></div><span className="account-state active">Aktif</span></div><div className="customer-summary"><div><span>Cüzdan</span><strong>{money(user.wallet)}</strong><small>Kullanılabilir</small></div><div><span>ProFlex</span><strong>{money(user.flex)}</strong><small>Yan hak</small></div><div><span>Cihaz</span><strong>{user.device.split(" · ")[0]}</strong><small>{user.device.split(" · ")[1]}</small></div><div><span>Risk</span><strong>{user.risk}</strong><small>{user.errors?user.errors+" hata incelenmeli":"Aktif hata yok"}</small></div></div><div className="assigned-cards"><div className="cards-title"><div><span className="eyebrow">ATANAN KARTLAR</span><h3>{user.cards.length?user.cards.length+" kart bağlı":"Kart bulunmuyor"}</h3></div>{!user.cards.length&&<button onClick={()=>notify("Kart atama akışı demo kuyruğuna alındı")}>Kart ata</button>}</div>{user.cards.length?<div className="card-grid">{user.cards.map(card=><article className={`payment-card ${card.type}`} key={card.type}><div><span>{card.type==="wallet"?"CÜZDAN":"PROFLEX"}</span><CreditCard/></div><strong>•••• •••• •••• {card.last4}</strong><footer><span>{card.label}<small>Son kullanım {card.expiry}</small></span><b className={card.status==="Blokeli"?"blocked":""}>{card.status}</b></footer></article>)}</div>:<div className="no-card"><CreditCard/><div><strong>Bu kullanıcıya kart atanmamış</strong><span>Kart atama problemi ve uygunluk kontrolleri için hazır senaryo.</span></div></div>}</div>
 <div className="log-analytics"><div className="analytics-head"><div><span className="eyebrow">SERVİS ANALİZİ</span><h3>{period==="daily"?"Günlük trafik":"Haftalık trafik"}</h3></div><div><button className={period==="daily"?"active":""} onClick={()=>setPeriod("daily")}>Günlük</button><button className={period==="weekly"?"active":""} onClick={()=>setPeriod("weekly")}>Haftalık</button></div></div><div className="bar-chart">{(period==="daily"?[42,61,48,79,68,91,74,83]:[55,69,63,82,76,88,71]).map((v,i)=><div key={i}><span style={{height:v+"%"}}><i style={{height:(8+i%4*3)+"%"}}/></span><small>{period==="daily"?pad(9+i*2)+":00":["Pzt","Sal","Çar","Per","Cum","Cmt","Paz"][i]}</small></div>)}</div><div className="chart-legend"><span><i/>Başarılı</span><span><i/>Hatalı</span><strong>{period==="daily"?"18.420 istek · %1,8 hata":"121.806 istek · %1,6 hata"}</strong></div></div><div className="journey-toolbar"><div><h3>Olay ve log akışı</h3><p>En yeniden eskiye tüm temas noktaları.</p></div><div>{[["all","Tümü"],["error","Hatalar"],["payment","Ödemeler"],["login","Girişler"]].map(x=><button className={kind===x[0]?"active":""} onClick={()=>setKind(x[0])} key={x[0]}>{x[1]}</button>)}</div></div>
 <div className="timeline">{shown.map((e,i)=>{const Icon=e.state==="error"?XCircle:e.state==="warning"?AlertTriangle:e.amount?CreditCard:e.action.includes("giriş")?LogIn:CheckCircle2;return <article className={`timeline-event ${e.state}`} key={e.id}><div className="timeline-line"><span><Icon/></span>{i<shown.length-1&&<i/>}</div><div className="event-card"><div className="event-top"><div><small>{e.service}</small><h4>{e.action}</h4></div><time>{e.time}</time></div><p>{e.detail}</p>{e.amount&&<div className="amount-row"><span>İşlem tutarı</span><strong>{money(e.amount)}</strong></div>}<div className="request-detail"><span><b>Endpoint</b><code>{e.service==="Money Cüzdan"?"/v2/wallet/transactions":e.service==="Money ProFlex"?"/v1/flex/entitlements":e.service==="Kimlik Servisi"?"/oauth/token":"/v3/mobile/session"}</code></span><span><b>Method / Status</b><code>{e.action.includes("giriş")?"POST":"GET"} · {e.state==="error"?"500":"200"}</code></span><span><b>Request ID</b><code>req_{e.trace.slice(3)}</code></span><span><b>Yanıt</b><code>{e.state==="error"?`{ error: ${e.code} }`:"{ success: true }"}</code></span></div><div className="log-row"><code>{e.code??"HTTP_200"}</code><span>{e.ms} ms</span><button onClick={()=>notify("İz kimliği kopyalandı")}><Copy/>{e.trace}</button></div></div></article>})}</div>
 <div className="action-grid" id="actions"><button onClick={()=>notify(user.id+" oturumu kontrol edildi")}><span><RefreshCw/></span><div><strong>Oturumu kontrol et</strong><small>Token ve cihaz oturumlarını doğrula</small></div><ChevronRight/></button><button onClick={()=>notify(user.id+" bakiyesi doğrulandı")}><span><WalletCards/></span><div><strong>Bakiyeyi doğrula</strong><small>Ledger ve uygulama bakiyesini karşılaştır</small></div><ChevronRight/></button></div></section></section></div>{toast&&<div className="toast"><CheckCircle2/>{toast}</div>}</section></main>}
